[build]
    publish = "public"
    command = "npm run build"
    functions = "functions"

[context.production]
    environment = { GATSBY_SHEET_LINK= "https://script.google.com/macros/s/AKfycbzgNeTn25D6r49hmqV-oUHS0WDJidbgZggmQ9e0pmqq9Q3TLqbQV9BFtAlpB2MyNRCj/exec", SENDINBLUE_API_KEY= "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"}

[dev]
    command= "npm run start"

[functions]
    directory = "/functions"