[build]
    publish = "public"
    command = "npm run build"
    functions = "functions"

[context.production]
    environment = { GATSBY_SHEET_LINK= "", SENDINBLUE_API_KEY= ""}

[dev]
    command= "npm run start"

[functions]
    directory = "/functions"